### PR TITLE
Strip 'code' param

### LINKED ISSUE #877: Facebook SDK not working for me (solved) (bug)
Just a quick note to explain the problem and its solution: copying and pasting example code returns an error 191 telling that the callback url isn't allowed and pointing you to app settings inside facebook.
What? It's impossible! Check multiple times.. No.. the url is right! So, why?

Solution 1 add callback url to getAccessToken in your code:
$accessToken = $helper->getAccessToken("http://www.yoursite.com/fb-callback.php");

Solution 2 edit facebook sdk code:
https://github.com/facebook/php-graph-sdk/blob/2f9639c15ae043911f40ffe44080b32bac2c5280/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L226
Edit this line, find ['state'] and add code ['state','code']
Code param isn't stripped from callback url by the helper so it's sent to fb and you get the error.

### PR DESCRIPTION
**Pull request by martinstuecklschwaiger**
This pull request fixes #877, since there hasn't been any activity in #905 for 25 days. 

I also adjusted the test to reflect the change and prevent accidental breaking in the future. 

I also changed the return value of `FooRedirectLoginOAuth2Client::getAccessTokenFromCode()` since that's the specified behavior in `OAuth2Client`. 

Please note that this fix is needed for “Strict Redirect URI Matching” which will be required by Facebook in March.

### CODE REVIEW

**Comment by Savageman** [comment]
Thanks a ton for this! I was just working on the upgrade for "Strict Redirect URI Matching" today and it's not working because of that...
We need this PR accepted :)

**Comment by martinstuecklschwaiger** [comment]
@yguedidi I hope I'm not annoying you but is there any change to get this pull request (or #905) merged soon?

File: tests/Helpers/FacebookRedirectLoginHelperTest.php [hunk 1]
```diff
@@ -97,9 +97,14 @@ public function testAnAccessTokenCanBeObtainedFromRedirect()
         $_GET['state'] = 'foo_state';
         $_GET['code'] = 'foo_code';
 
-        $accessToken = $this->redirectLoginHelper->getAccessToken(self::REDIRECT_URL);
+        $fullUrl = self::REDIRECT_URL . '?state=foo_state&code=foo_code&some_param=blah';
```
Comment (gmertk) [inline tests/Helpers/FacebookRedirectLoginHelperTest.php]: May use const for the text "foo_state" "foo_code" and "some_param=blah"

**Comment by gmertk** [comment]
@yguedidi if it looks good to you, let's get this going! :)

**Comment by martinstuecklschwaiger** [comment]
@gmertk better now?

**Comment by yguedidi** [comment]
@martinstuecklschwaiger 5.6.2 released! Thanks again for the PR! Thanks @gmertk for your help in review!

**Comment by hao214** [comment]
my callback url is http://www.example.dk/fb/fbcallback.php?id=### how can I define this

please help

**Comment by yguedidi** [comment]
@hao214 if you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

**Comment by alexwai** [comment]
Finally i manage to find the problem when using the  PHP SDK.

The message that always shows is "The domain of this URL isn't included in the app's domains."

On the callback page in the getAccessToken need to specify the call back url even thou it is optional

```
try 
{
	$accessToken = $helper->getAccessToken('https://place-your-callback-url-here');
} 
catch (\Facebook\Exceptions\FacebookResponseException $e) 
{
	echo $e->getMessage();
} 
catch (\Facebook\Exceptions\FacebookSDKException $e) 
{

	echo $e->getMessage();
}
if (!$accessToken) 
{
	echo 'FAIL';
}
```

Hope this helps......
